server:
  port: 8072

# EUREKA CLIENT
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    # Em ambiente Docker, descomente a linha abaixo:
    # defaultZone: http://eurekaserver:8070/eureka/

# CLOUD GATEWAY
spring:
  cloud:
    config:
     import-check.enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: licensing-service
          uri: lb://licensing-service
          predicates:
            - Path=/licensing/**
          filters:
            - RewritePath=/licensing/(?<path>.*), /$\{path}

# ACTUATOR MANAGEMENT
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,gateway